Repository mezzio/mezzio-swoole, pull requests merged in 2021-12, with the labels that each got.

#74 Provide PHP 8.1 support
  .laminas-ci.json
  composer.json
  composer.lock
  phpunit.xml.dist
  psalm-baseline.xml
  src/StaticResourceHandler/LastModifiedMiddleware.php
  src/Task/ServiceBasedTask.php
  src/Task/Task.php
  test/FormatTimestampTrait.php
  test/StaticResourceHandler/IntegrationMappedTest.php
  test/StaticResourceHandler/IntegrationTest.php
  test/StaticResourceHandler/LastModifiedMiddlewareTest.php
Labels: Enhancement

#75 Fix deprecation in request time formatting for access logs
  psalm.xml.dist
  src/Log/AccessLogDataMap.php
  src/Log/StrftimeToICUFormatMap.php
  test/Log/AccessLogDataMapTest.php
  test/Log/StrftimeToICUFormatMapTest.php
Labels: Bug

#77 Added support for symfony/console 6.0
  composer.json
Labels: Enhancement

#79 Fix error flagged by Psalm
  psalm-baseline.xml
  src/HotCodeReload/FileWatcher/InotifyFileWatcher.php
Labels: Enhancement

#80 Replace documentation for disabling static resources
  docs/book/v3/static-resources.md
  src/ConfigProvider.php
Labels: Bug, Documentation

#81 Document proper aggregation of Swoole ConfigProvider
  docs/book/v3/cookbook/swoole-not-starting.md
  mkdocs.yml
  src/ConfigProvider.php
Labels: Documentation
